app = 'flyio-minecraft'
primary_region = 'nrt'

[build]

[env]
EULA = 'TRUE'
TYPE = 'VANILLA'
VERSION = '26.2'
MEMORY = '3800M'

[[mounts]]
source = 'minecraft_data'
destination = '/data'

[[vm]]
memory = '4gb'
cpu_kind = 'performance'
cpus = 1

[[services]]
internal_port = 25565
protocol = 'tcp'

[[services.ports]]
port = 25565
handlers = []

[[services.tcp_checks]]
interval = '15s'
timeout = '2s'
