# fly.toml app configuration file generated for flyio-minecraft on 2026-07-26T01:47:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flyio-minecraft'
primary_region = 'nrt'

[build]

[env]
EULA = 'TRUE'
TYPE = 'VANILLA'
VERSION = '26.2'

[[mounts]]
source = 'minecraft_data'
destination = '/data'

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
memory_mb = 256

[[services]]
internal_port = 25565
protocol = "tcp"

[[services.ports]]
port = 25565
